"""Add fraud engines schemas

Revision ID: b6eb9c8b45a9
Revises: 0e50e23a8438
Create Date: 2026-07-12 15:27:53.065654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6eb9c8b45a9'
down_revision: Union[str, Sequence[str], None] = '0e50e23a8438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE transactionstatus ADD VALUE 'PROCESSING'")
    op.create_table('blacklisted_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_value', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklisted_entities_entity_type'), 'blacklisted_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_blacklisted_entities_entity_value'), 'blacklisted_entities', ['entity_value'], unique=False)
    op.create_index(op.f('ix_blacklisted_entities_id'), 'blacklisted_entities', ['id'], unique=False)
    op.create_table('analyst_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('analyst_id', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_analyst_decisions_id'), 'analyst_decisions', ['id'], unique=False)
    op.create_table('fraud_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('rule_engine_score', sa.Float(), nullable=False),
    sa.Column('ml_anomaly_score', sa.Float(), nullable=False),
    sa.Column('graph_risk_score', sa.Float(), nullable=False),
    sa.Column('aggregated_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('triggered_rules', sa.JSON(), nullable=False),
    sa.Column('ml_details', sa.JSON(), nullable=False),
    sa.Column('graph_details', sa.JSON(), nullable=False),
    sa.Column('customer_explanation', sa.Text(), nullable=True),
    sa.Column('analyst_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_fraud_evaluations_id'), 'fraud_evaluations', ['id'], unique=False)
    op.add_column('transactions', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('transactions', sa.Column('merchant_category', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('country', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'country')
    op.drop_column('transactions', 'merchant_category')
    op.drop_column('transactions', 'ip_address')
    op.drop_index(op.f('ix_fraud_evaluations_id'), table_name='fraud_evaluations')
    op.drop_table('fraud_evaluations')
    op.drop_index(op.f('ix_analyst_decisions_id'), table_name='analyst_decisions')
    op.drop_table('analyst_decisions')
    op.drop_index(op.f('ix_blacklisted_entities_id'), table_name='blacklisted_entities')
    op.drop_index(op.f('ix_blacklisted_entities_entity_value'), table_name='blacklisted_entities')
    op.drop_index(op.f('ix_blacklisted_entities_entity_type'), table_name='blacklisted_entities')
    op.drop_table('blacklisted_entities')
    # ### end Alembic commands ###
